title: Meilin Blog-in-Progress
author: Meilin
email: meilin.ossanna@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Learning to create blog site via GitHub; pending pictures

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
